### ISSUE TITLE
[SOLVED] Got 404 when visiting layout page

### ISSUE THREAD

**Issue by jan-warchol** [abalanna/klawiatura#1]
When I tried opening the link in the pdf (https://configure.ergodox-ez.com/keyboard-layouts/kdmvjm), I got an error:
```
The page you were looking for doesn't exist.
You may have mistyped the address or the page may have moved.
```

**Comment by abalanna** [comment]
The correct link is: https://configure.ergodox-ez.com/keyboard_layouts/kdmvjm :)
